version: '3'

networks:
  net:
    driver: bridge

services:
  db:
    networks:
      - net
    image: postgres:15.6-alpine3.19
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daeseong0226
      POSTGRES_PASSWORD: 230308
      POSTGRES_DB: newoffice
    cpus: '0.5'
    mem_limit: '0.5g'
